### PR TITLE
additional functionality for diffing

### PR DESCRIPTION
**Pull request by Chonghao**
I built on top of the srx folder. My diffing function now takes in json files as inputs and outputs diffs in both json and pickle format. I also used python's multiprocessing library to parallelize generation of allow rules and diffing of allow rules.  
My output diff contains additional information on which old rule and new rule in the two policies induced the change.

### CODE REVIEW

**Comment by whyzgeek** [comment]
Hey Dustin, Chonghao developed this based on some requirements we had internally in Bloomberg as his summer project. Following was our design guidelines:

- Decouple from SRX to become more general. Currently we added json abstraction for any firewall. We developed an internal tool to extract policies from Tufin XML output to this json format. 
- Change the design that can be parallelized to any MapReduce framework. Currently implemented against multiprocessing module. 
- We solely focused on diff and generating allow rules functionality. We are in planning phase to add a firewall optimization module. (removing shadow or partial shadow rules, ,..)
- Add rule numbers to diff output

I know above might not fully integrate into your original vision of creating this module but I think it would be huge contribution to expand this and make it a full fledged firewall toolkit module that can be used for firewall automation and policy reviews and TDD of firewall rules. However if you don't think this is good idea or this is not the place for it, let us know.

**Comment by djmitche** [comment]
Thanks for the context -- I'm having a look now.

**Comment by djmitche** [comment]
So first, I'm not totally sure what this does -- it lacks any documentation update that might guide me, and has few docstrings or comments to help.  The diffstat (+2,075 −1) suggests, as does a read through the added code, that you were very careful not to change anything that's already in place, at the cost of adding duplicate code and functionality.

It *looks* like this adds a new policy type, "json", although judging from the strings and functionality that's really just another version of the existing "srx" policy type -- it involves zones and table "inet.0" and so on.  So (again, not really understanding what the intent was) it seems like this should have been a modification to the srx policy type, rather than a new policy type.  We already support two policy types (AWS security group and SRX), so I don't understand what sort of decoupling was required.

I'd love to see a Tufin policy type that simply reads the Tufin XML.

I love the idea of using multiprocessing and/or MapReduce to shard the diff operation.  It would be neat to do a similar thing with the policy processing.

I'm not sure why there are separate "diff" and "diff-json" commands -- does the latter output in JSON?

What is an "allow rule"?

Regarding the tests -- awesome to see tests in this PR!  I think they are failing because gen_allow_simple3/apps/ has not been added with 'git add'?

Overall, then, I don't object to any of this, but I'd like to see these ideas implemented as individual pull requests that modify, rather than bolt onto, fwunit.

**Comment by Chonghao** [comment]
Thanks for the reply.
I just fixed the tests. The apps directory was created by my program. I forgot to ensure they were created in the tests.
The original goal of my summer project was to mimic Tufin's diffing functionality but do it faster by doing the diffing on a cluster of machines in parallel. It is naturally parallelizable since one assumption of fwunit is that applications don't interfere with each other.
A handy functionality that Tufin has is that for a newly blocked flow, it tells you the rule number in the old policy that permitted the flow and the rule number in the new policy that blocks the flow. Tufin will also tell you the old and new rule number for newly allowed flows. I added this functionality to fwunit.
You are right that the json directory I added overlaps with srx. I didn't directly modify src since it would break all your tests(my outputs are quite different from yours, with additional information).
The same rationale goes for "dfff" amd "diff-json". I didn't want to break your tests. "diff-json" reads in policies as json files and outputs them in both json and python pickle format.
The input policies contain both allow and deny rules. By "allow rules" I mean a set of allow rules that is equivalent to the input allow and deny rules.

**Comment by djmitche** [comment]
Thanks for the explanation.

To merge this, I would want to see the following.
 * break into a few separate pull requests; perhaps one for parallel diffs, one for tracking rule numbers and displaying them in diffs, one for allow rules (I'm still not sure what these are since you defined them as "allow rules"), and one adding a Tufin policy type.
 * for each:
   * integrate the functionality into existing code, rather than adding it on the side, and update existing tests to handle the new behavior
   * update documentation, both README and Sphinx docs
   * check for good code style -- no [commented-out functions](d6aec17), for example.

I know that's a lot of work and a substantial change from what you've written, but it's necessary to allow further maintenance and development of the fwunit project.  Any one of the mentioned pull requests would be great to have alone, if you do not have the time to create all of them.

**Comment by whyzgeek** [comment]
I am on board on all the points Dustin suggested and thanks for accepting full integration. One note on adding Tufin as the source, the reasons we went for json was following:

* The current design suggest we add more FW devices.(We are planning on Checkpoint and Cisco) However, these usually have dependency on other eggs which can over time increase complexity of current module. There are some other projects that deal with device abstraction (like napalm) and I don't know if it is appropriate to repeat the whole or partial logic in the current module. That's the context for choosing json as intermediary format which also enables being able to run the module offline independently using a uniform input file.
* We thought SRX is a great model that every other firewall model can be converted to it as default standard model.

Chonghauo, I will take care of creating the pull request for Tufin part.

**Comment by djmitche** [comment]
The dependencies on other eggs are handled with the "]extras_require](https://github.com/mozilla/build-fwunit/blob/master/setup.py#L31)" support in setup.py.  You'll notice a few dependencies are already specific to the SRX.  So having policy-source-specific requirements is fine.

That said, using Tufin as an intermediary is also fine, and maybe it makes sense to add options to read data via Tufin for existing policy sources.  For example, for SRX perhaps there's a "from-tufin-export: tufin-export.json" option in `fwunit.yml` that causes it to skip ssh'ing to the firewall and instead just read in the given JSON file.

As for your second bullet point, fwunit already has a general model for rules -- the rules database.  The idea is that all policy sources should convert to this format.  So I don't think there's a great need for an additional "standard model", and particularly not for one that incorporates such Juniper-specific concepts as zones and groups.  If it turns out that there is some common code involved in parsing, say, Cisco and Juniper rules (or for example in parsing Tufin XML or JSON), I think it would be fine to factor that code out into a utility module that both policy sources share.

**Pull request closed without merging**
